# Generated by Django 4.0 on 2022-01-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturant',
            name='tags',
        ),
        migrations.AddField(
            model_name='resturant',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
